title: Wenhao Fu's Homepage
page-top-title: Wenhao Fu
top-section-bg-text: Explore. Prove. Iterate.
home-subtitle: Wenhao Fu's Homepage&ensp;|&ensp;付文豪 的个人主页
copyright-text: '&copy; Wenhao Fu 2025-2025. All Rights Reserved.'
