title: Wenhao Fu's Homepage
page-top-title: Wenhao Fu
top-section-bg-text: Be what you wanna be
home-subtitle: Wenhao Fu&ensp;|&ensp;付文豪
copyright-text: '&copy; Wenhao Fu 2023-2025. All Rights Reserved.'
